# Generated by Django 4.2.8 on 2023-12-30 00:47

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading_text", wagtail.blocks.CharBlock(form_classname="title", required=True)),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select a header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(icon="pilcrow", template="blocks/paragraph_block.html"),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "block",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "attribute_name",
                                    wagtail.blocks.CharBlock(blank=True, label="e.g. Mary Berry", required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "accordion",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "accordion_item",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(help_text="Add your title", required=True),
                                            ),
                                            (
                                                "content",
                                                wagtail.blocks.RichTextBlock(
                                                    help_text="Add your content", required=True
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ],
                            label_format="FAQ (Accordion)",
                        ),
                    ),
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.RawHTMLBlock(help_text="Add your title", required=True)),
                                (
                                    "sub_title",
                                    wagtail.blocks.CharBlock(help_text="Add your sub title", required=False),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                (
                                    "buttons",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Button display text", required=False
                                                    ),
                                                ),
                                                (
                                                    "page_link",
                                                    wagtail.blocks.PageChooserBlock(
                                                        help_text="Select an internal page to link to", required=False
                                                    ),
                                                ),
                                                (
                                                    "anchor",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Link to a anchor on the same page", required=False
                                                    ),
                                                ),
                                                (
                                                    "open_modal",
                                                    wagtail.blocks.BooleanBlock(
                                                        help_text="Open form modal", required=False
                                                    ),
                                                ),
                                                (
                                                    "style",
                                                    wagtail.blocks.ChoiceBlock(
                                                        blank=False,
                                                        choices=[
                                                            ("", "Select a style"),
                                                            ("primary", "Primary"),
                                                            ("secondary", "Secondary"),
                                                            ("light", "Light"),
                                                            ("dark", "Dark"),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "outline",
                                                    wagtail.blocks.BooleanBlock(
                                                        help_text="Make the button outline?", required=False
                                                    ),
                                                ),
                                            ],
                                            required=False,
                                        )
                                    ),
                                ),
                                (
                                    "usps",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [("text", wagtail.blocks.CharBlock(help_text="USP text", required=False))],
                                            required=False,
                                        )
                                    ),
                                ),
                                (
                                    "full_width",
                                    wagtail.blocks.BooleanBlock(help_text="Make hero full width", required=False),
                                ),
                            ],
                            label_format="Hero",
                        ),
                    ),
                    (
                        "review",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "max_count",
                                    wagtail.blocks.IntegerBlock(
                                        default=10, help_text="Maximum number of reviews to display", required=False
                                    ),
                                )
                            ],
                            label_format="Reviews",
                        ),
                    ),
                    (
                        "services",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Add your title", required=True)),
                                (
                                    "services",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Add your title, default to 'Your services'",
                                                        required=False,
                                                    ),
                                                ),
                                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                                (
                                                    "page_link",
                                                    wagtail.blocks.PageChooserBlock(
                                                        help_text="Select an internal page to link to", required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ],
                            label_format="Services",
                        ),
                    ),
                    (
                        "cases",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Add your title", required=False)),
                                ("subtitle", wagtail.blocks.CharBlock(help_text="Add your subtitle", required=False)),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(help_text="Add your description", required=True),
                                ),
                                (
                                    "cases",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Add your title", required=False
                                                    ),
                                                ),
                                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                                (
                                                    "page_link",
                                                    wagtail.blocks.PageChooserBlock(
                                                        help_text="Select an internal page to link to", required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ],
                            label_format="Cases",
                        ),
                    ),
                    (
                        "features",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Add your title", required=False)),
                                (
                                    "features",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Add your title", required=False
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Add your description", required=False
                                                    ),
                                                ),
                                                ("icon", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                            ]
                                        )
                                    ),
                                ),
                            ],
                            label_format="Features",
                        ),
                    ),
                    (
                        "masonry",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Add your title", required=False)),
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Add your title", required=False
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Add your description", required=False
                                                    ),
                                                ),
                                                ("icon", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                                (
                                                    "align_right",
                                                    wagtail.blocks.BooleanBlock(
                                                        help_text="Align the image to the right", required=False
                                                    ),
                                                ),
                                                (
                                                    "col_span",
                                                    wagtail.blocks.ChoiceBlock(
                                                        blank=True,
                                                        choices=[("", "Select a col-span"), ("1", "1"), ("2", "2")],
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ],
                            label_format="Masonry",
                        ),
                    ),
                    (
                        "text_image",
                        wagtail.blocks.StructBlock(
                            [
                                ("subtitle", wagtail.blocks.CharBlock(help_text="Add your subtitle", required=False)),
                                ("title", wagtail.blocks.CharBlock(help_text="Add your title", required=True)),
                                ("text", wagtail.blocks.RichTextBlock(help_text="Add your text", required=True)),
                                ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                (
                                    "embed",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks",
                                        icon="media",
                                        max_height=400,
                                        max_width=800,
                                        required=False,
                                    ),
                                ),
                                (
                                    "buttons",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Button display text", required=False
                                                    ),
                                                ),
                                                (
                                                    "page_link",
                                                    wagtail.blocks.PageChooserBlock(
                                                        help_text="Select an internal page to link to", required=False
                                                    ),
                                                ),
                                                (
                                                    "anchor",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Link to a anchor on the same page", required=False
                                                    ),
                                                ),
                                                (
                                                    "open_modal",
                                                    wagtail.blocks.BooleanBlock(
                                                        help_text="Open form modal", required=False
                                                    ),
                                                ),
                                                (
                                                    "style",
                                                    wagtail.blocks.ChoiceBlock(
                                                        blank=False,
                                                        choices=[
                                                            ("", "Select a style"),
                                                            ("primary", "Primary"),
                                                            ("secondary", "Secondary"),
                                                            ("light", "Light"),
                                                            ("dark", "Dark"),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "outline",
                                                    wagtail.blocks.BooleanBlock(
                                                        help_text="Make the button outline?", required=False
                                                    ),
                                                ),
                                            ],
                                            required=True,
                                        )
                                    ),
                                ),
                                (
                                    "reverse",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Reverse the order of text and image", required=False
                                    ),
                                ),
                                (
                                    "shadow",
                                    wagtail.blocks.BooleanBlock(help_text="Add a shadow to image", required=False),
                                ),
                            ],
                            label_format="Text & Image",
                        ),
                    ),
                    (
                        "page_list",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Add your title", required=True)),
                                ("text", wagtail.blocks.TextBlock(help_text="Add your text", required=False)),
                                (
                                    "pages",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Add your title", required=True
                                                    ),
                                                ),
                                                ("page", wagtail.blocks.PageChooserBlock(required=False)),
                                            ]
                                        )
                                    ),
                                ),
                            ],
                            label_format="List with pages",
                        ),
                    ),
                    (
                        "highlight",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Add your title", required=True)),
                                (
                                    "button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Button display text", required=False
                                                ),
                                            ),
                                            (
                                                "page_link",
                                                wagtail.blocks.PageChooserBlock(
                                                    help_text="Select an internal page to link to", required=False
                                                ),
                                            ),
                                            (
                                                "anchor",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Link to a anchor on the same page", required=False
                                                ),
                                            ),
                                            (
                                                "open_modal",
                                                wagtail.blocks.BooleanBlock(
                                                    help_text="Open form modal", required=False
                                                ),
                                            ),
                                            (
                                                "style",
                                                wagtail.blocks.ChoiceBlock(
                                                    blank=False,
                                                    choices=[
                                                        ("", "Select a style"),
                                                        ("primary", "Primary"),
                                                        ("secondary", "Secondary"),
                                                        ("light", "Light"),
                                                        ("dark", "Dark"),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "outline",
                                                wagtail.blocks.BooleanBlock(
                                                    help_text="Make the button outline?", required=False
                                                ),
                                            ),
                                        ],
                                        required=True,
                                    ),
                                ),
                            ],
                            label_format="Highlight",
                        ),
                    ),
                    (
                        "anchor",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "anchor_tag",
                                    wagtail.blocks.CharBlock(help_text="Write a tag you remember", required=False),
                                )
                            ],
                            label_format="Anchor",
                        ),
                    ),
                    (
                        "empty_space",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background_color",
                                    wagtail.blocks.BooleanBlock(help_text="Add background color", required=False),
                                )
                            ],
                            label_format="Empty Space",
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Page body",
            ),
        ),
    ]
