# Generated by Django 4.2.8 on 2024-01-30 07:29

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0004_alter_standardpage_body_custommainmenuitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading_text", wagtail.blocks.CharBlock(form_classname="title", required=True)),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Vælg en overskriftsstørrelse"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(icon="pilcrow", template="blocks/paragraph_block.html"),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "block",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "attribute_name",
                                    wagtail.blocks.CharBlock(blank=True, label="f.eks. Mona Lisa", required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "accordion",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "accordion_item",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(help_text="Tilføj din titel", required=True),
                                            ),
                                            (
                                                "content",
                                                wagtail.blocks.RichTextBlock(
                                                    help_text="Tilføj dit indhold", required=True
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ],
                            label_format="FAQ (Akkordeon)",
                        ),
                    ),
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.RawHTMLBlock(help_text="Tilføj din titel", required=True)),
                                (
                                    "sub_title",
                                    wagtail.blocks.RawHTMLBlock(help_text="Tilføj din undertitel", required=False),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                (
                                    "buttons",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Knap visningstekst", required=False
                                                    ),
                                                ),
                                                (
                                                    "page_link",
                                                    wagtail.blocks.PageChooserBlock(
                                                        help_text="Vælg en intern side at linke til", required=False
                                                    ),
                                                ),
                                                (
                                                    "anchor",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Link til et anker på samme side", required=False
                                                    ),
                                                ),
                                                (
                                                    "open_modal",
                                                    wagtail.blocks.BooleanBlock(
                                                        help_text="Åbn formularmodal", required=False
                                                    ),
                                                ),
                                                (
                                                    "style",
                                                    wagtail.blocks.ChoiceBlock(
                                                        blank=False,
                                                        choices=[
                                                            ("", "Vælg en stil"),
                                                            ("primary", "Primær"),
                                                            ("secondary", "Sekundær"),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                            ],
                                            required=False,
                                        )
                                    ),
                                ),
                                (
                                    "usps",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "text",
                                                    wagtail.blocks.CharBlock(help_text="USP-tekst", required=False),
                                                )
                                            ],
                                            required=False,
                                        )
                                    ),
                                ),
                                (
                                    "full_width",
                                    wagtail.blocks.BooleanBlock(help_text="Gør helten fuld bredde", required=False),
                                ),
                            ],
                            label_format="Hero",
                        ),
                    ),
                    (
                        "review",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "max_count",
                                    wagtail.blocks.IntegerBlock(
                                        default=10, help_text="Maksimalt antal anmeldelser til visning", required=False
                                    ),
                                )
                            ],
                            label_format="Anmeldelser",
                        ),
                    ),
                    (
                        "services",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Add your title", required=True)),
                                (
                                    "services",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Tilføj din titel", required=False
                                                    ),
                                                ),
                                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                                (
                                                    "page_link",
                                                    wagtail.blocks.PageChooserBlock(
                                                        help_text="Vælg en intern side at linke til", required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ],
                            label_format="Tjenester",
                        ),
                    ),
                    (
                        "cases",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Tilføj din titel", required=False)),
                                (
                                    "subtitle",
                                    wagtail.blocks.CharBlock(help_text="Tilføj din undertekst", required=False),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(help_text="Tilføj din beskrivelse", required=True),
                                ),
                                (
                                    "cases",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(help_text="Tjenester", required=False),
                                                ),
                                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                                (
                                                    "page_link",
                                                    wagtail.blocks.PageChooserBlock(
                                                        help_text="Vælg en intern side at linke til", required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ],
                            label_format="Fremvisninger",
                        ),
                    ),
                    (
                        "features",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Add your title", required=False)),
                                (
                                    "features",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Tilføj din titel", required=False
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Tilføj din beskrivelse", required=False
                                                    ),
                                                ),
                                                ("icon", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                            ]
                                        )
                                    ),
                                ),
                            ],
                            label_format="Funktioner",
                        ),
                    ),
                    (
                        "masonry",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Tilføj din titel", required=False)),
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(help_text="Funktioner", required=False),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Tilføj din beskrivelse", required=False
                                                    ),
                                                ),
                                                ("icon", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                                (
                                                    "align_right",
                                                    wagtail.blocks.BooleanBlock(
                                                        help_text="Juster billedet til højre", required=False
                                                    ),
                                                ),
                                                (
                                                    "col_span",
                                                    wagtail.blocks.ChoiceBlock(
                                                        blank=True,
                                                        choices=[("", "Vælg en col-span"), ("1", "1"), ("2", "2")],
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "is_premium",
                                                    wagtail.blocks.BooleanBlock(
                                                        help_text="Giv en speciel 'premium' badge", required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ],
                            label_format="Tegl",
                        ),
                    ),
                    (
                        "text_image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "subtitle",
                                    wagtail.blocks.CharBlock(help_text="Tilføj din undertekst", required=False),
                                ),
                                ("title", wagtail.blocks.CharBlock(help_text="Tilføj din titel", required=True)),
                                ("text", wagtail.blocks.RichTextBlock(help_text="Tilføj din tekst", required=True)),
                                ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                (
                                    "embed",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Indsæt en indlejret URL f.eks https://www.youtube.com/watch?v=SGJFWirQ3ks",
                                        icon="media",
                                        max_height=400,
                                        max_width=800,
                                        required=False,
                                    ),
                                ),
                                (
                                    "buttons",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Knap visningstekst", required=False
                                                    ),
                                                ),
                                                (
                                                    "page_link",
                                                    wagtail.blocks.PageChooserBlock(
                                                        help_text="Vælg en intern side at linke til", required=False
                                                    ),
                                                ),
                                                (
                                                    "anchor",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Link til et anker på samme side", required=False
                                                    ),
                                                ),
                                                (
                                                    "open_modal",
                                                    wagtail.blocks.BooleanBlock(
                                                        help_text="Åbn formularmodal", required=False
                                                    ),
                                                ),
                                                (
                                                    "style",
                                                    wagtail.blocks.ChoiceBlock(
                                                        blank=False,
                                                        choices=[
                                                            ("", "Vælg en stil"),
                                                            ("primary", "Primær"),
                                                            ("secondary", "Sekundær"),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                            ],
                                            required=True,
                                        )
                                    ),
                                ),
                                (
                                    "reverse",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Omvend rækkefølgen af tekst og billede", required=False
                                    ),
                                ),
                            ],
                            label_format="Tekst & Billede",
                        ),
                    ),
                    (
                        "text_image_repeater",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "subtitle",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Tilføj din undertekst", required=False
                                                    ),
                                                ),
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Tilføj din titel", required=True
                                                    ),
                                                ),
                                                (
                                                    "text",
                                                    wagtail.blocks.RichTextBlock(
                                                        help_text="Tilføj din tekst", required=True
                                                    ),
                                                ),
                                                ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                (
                                                    "embed",
                                                    wagtail.embeds.blocks.EmbedBlock(
                                                        help_text="Indsæt en indlejret URL f.eks https://www.youtube.com/watch?v=SGJFWirQ3ks",
                                                        icon="media",
                                                        max_height=400,
                                                        max_width=800,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "buttons",
                                                    wagtail.blocks.ListBlock(
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="Knap visningstekst", required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "page_link",
                                                                    wagtail.blocks.PageChooserBlock(
                                                                        help_text="Vælg en intern side at linke til",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "anchor",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="Link til et anker på samme side",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "open_modal",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        help_text="Åbn formularmodal", required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "style",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        blank=False,
                                                                        choices=[
                                                                            ("", "Vælg en stil"),
                                                                            ("primary", "Primær"),
                                                                            ("secondary", "Sekundær"),
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ],
                                                            required=True,
                                                        )
                                                    ),
                                                ),
                                                (
                                                    "reverse",
                                                    wagtail.blocks.BooleanBlock(
                                                        help_text="Omvend rækkefølgen af tekst og billede",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ],
                            label_format="Tekst & Billede Gentager",
                        ),
                    ),
                    (
                        "page_list",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Tilføj din titel", required=True)),
                                ("text", wagtail.blocks.TextBlock(help_text="Tilføj din tekst", required=False)),
                                (
                                    "pages",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Tilføj din titel", required=True
                                                    ),
                                                ),
                                                ("page", wagtail.blocks.PageChooserBlock(required=False)),
                                            ]
                                        )
                                    ),
                                ),
                            ],
                            label_format="Liste med sider",
                        ),
                    ),
                    (
                        "highlight",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Tilføj din titel", required=True)),
                                (
                                    "button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Knap visningstekst", required=False
                                                ),
                                            ),
                                            (
                                                "page_link",
                                                wagtail.blocks.PageChooserBlock(
                                                    help_text="Vælg en intern side at linke til", required=False
                                                ),
                                            ),
                                            (
                                                "anchor",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Link til et anker på samme side", required=False
                                                ),
                                            ),
                                            (
                                                "open_modal",
                                                wagtail.blocks.BooleanBlock(
                                                    help_text="Åbn formularmodal", required=False
                                                ),
                                            ),
                                            (
                                                "style",
                                                wagtail.blocks.ChoiceBlock(
                                                    blank=False,
                                                    choices=[
                                                        ("", "Vælg en stil"),
                                                        ("primary", "Primær"),
                                                        ("secondary", "Sekundær"),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        required=True,
                                    ),
                                ),
                            ],
                            label_format="Fremhæv",
                        ),
                    ),
                    (
                        "anchor",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "anchor_tag",
                                    wagtail.blocks.CharBlock(help_text="Write a tag you remember", required=False),
                                )
                            ],
                            label_format="Anker",
                        ),
                    ),
                    (
                        "empty_space",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background_color",
                                    wagtail.blocks.BooleanBlock(help_text="Tilføj baggrundsfarve", required=False),
                                )
                            ],
                            label_format="Tomt Rum",
                        ),
                    ),
                    ("audit_form", wagtail.blocks.StructBlock([], label_format="Audit Form")),
                    (
                        "price_table",
                        wagtail.blocks.StructBlock(
                            [("image", wagtail.images.blocks.ImageChooserBlock(required=False))],
                            label_format="Pris tabel",
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Page body",
            ),
        ),
    ]
