# Generated by Django 4.2.8 on 2024-02-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autoarticles", "0002_articletopic_sitemapcompetitor_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SitemapCompetitor",
        ),
        migrations.AddField(
            model_name="articletopic",
            name="has_article",
            field=models.BooleanField(default=False, help_text="Determines if an article has been written"),
        ),
        migrations.AlterField(
            model_name="articletopic",
            name="is_parsed",
            field=models.BooleanField(default=False, help_text="Determines if the link can be scraped and parsed"),
        ),
        migrations.AlterField(
            model_name="articletopic",
            name="is_ready",
            field=models.BooleanField(default=False, help_text="Determines if a article can be written"),
        ),
    ]
