# Generated by Django 4.2.8 on 2023-12-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Navn")),
                ("website", models.CharField(max_length=100, verbose_name="Hjemmeside")),
                ("email", models.EmailField(max_length=100, verbose_name="E-mail")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("video_url", models.CharField(blank=True, max_length=255, null=True, verbose_name="Video link")),
            ],
        ),
    ]
