# Generated by Django 4.2.8 on 2024-01-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="video_url",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Videolink"),
        ),
    ]
